apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
spec:
  rules:
  - host: sample.web.lk
    http:
      paths:
      - backend:
          serviceName: nginxing-service
          servicePort:  80
