apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  namespace:  ngroshan
spec:
  rules:
  - host: roshan.nginx.com
    http:
      paths:
      - backend:
          serviceName: nginxing-service
          servicePort:  80
