apiVersion: v1
stringData:
  CASSANDRA_CLUSTERNAME: CSI
  CASSANDRA_PASSWORD: admin
  CASSANDRA_USERNAME: admin
  CICD_PASSWORD_ADMIN: db@tmp
  CICD_USERNAME_ADMIN: csi_dev_tmp
  CSI_JPA_EVENT_RABBITMQ_PASSWORD: admin
  CSI_JPA_EVENT_RABBITMQ_USERNAME: admin
  SPRING_RABBITMQ_PASSWORD: admin
  SPRING_RABBITMQ_USERNAME: admin
  password: devlkcsi@2017
  username: devlkcsi
kind: Secret
metadata:
  name: service-configs-secret
type: Opaque
