apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: Healthcare-app-ingress
  namespace: prod
spec:
  rules:
  - host: health.tsolution.lk
    http:
      paths:
      - backend:
          service:
            name: Healthcare-app
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
